### PR TITLE
Maintenance refresh, part 3: code cleanup

### PR DESCRIPTION
**Pull request by jnpkrn**
Expects #29 merged.

### CODE REVIEW

**Comment by jnpkrn** [comment]
Note that this PR is still unfinished, I am working towards handling
the limitations imposed with limited static buffers more gracefully
so at to be explicit about possible truncations.

**Comment by jnpkrn** [comment]
Ok, that's now done with 52f255a.

**Comment by jnpkrn** [comment]
Rebased on current master.

**Comment by dmuhamedagic** [comment]
On Tue, Apr 26, 2016 at 07:32:19AM -0700, Jan Pokorný wrote:
> Rebased on current master.

I did that on the command line, before merging.

Good work!

**Comment by dmuhamedagic** [comment]
Hmm, strange that this is not shown as merged.

**Comment by jnpkrn** [comment]
NM, I see it merged: commit 0cd99ac.

I find it PITA to work with GH merge system at times, for instance
it cannot infer dependency/containment amongst the PRs, so the
unability to catch up with out-of-projected workflow comes as no
surprise.

**Comment by jnpkrn** [comment]
And thanks for the reviews and merging.
Let me know what you think of cluster-glue opt-out PR (#22).

**Pull request closed without merging**
