### PR TITLE
Test: python3 support + slight refactorting/cleanup

### PR DESCRIPTION
**Pull request by jnpkrn**
More likely to come, though feel free to review/merge existing part,
will open a new PR if need be.

### CODE REVIEW

**Comment by jnpkrn** [comment]
Forgot about setting `test/runtests.py` executable once it is prepared in `configure`
processing.

**Comment by jnpkrn** [comment]
Added some more maintenance-like commits.

**Comment by dmuhamedagic** [comment]
Looks fine to me, though I've never done python 2->3. I believe that this part was done by @phmarek , maybe he wants to take a look too.

**Comment by phmarek** [comment]
Sorry, I don't have that much experience either... 
A cursory view looks good to me; as @dmuhamedagic is also fine with that I'll just merge.

Thanks a lot!

**Pull request merged**
