### PR TITLE
Use pkg-config to configure libxml-2.0

### PR DESCRIPTION
**Pull request by vvidic**
xml2-config will be removed from Debian

### CODE REVIEW

**Comment by jnpkrn** [comment]
LGTM, but would you mind referencing the triggering event?
Otherwise it'd remain semi-opaque why this change was made
in the first place, something that may cause head scratching
in the future.

Looks like the missing link is:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949057

**Comment by vvidic** [comment]
On Mon, Jan 20, 2020 at 06:37:49AM -0800, Jan Pokorný wrote:
> LGTM, but would you mind referencing the triggering event?
> Otherwise it'd remain semi-opaque why this change was made
> in the first place, something that may cause head scratching
> in the future.
> 
> Looks like the missing link is:
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949057

Yep, not sure if the removal of xml2-config is Debian specific,
but I guess anyway it is better to use pkg-config if possible.

-- 
Valentin

**Comment by jnpkrn** [comment]
> Yep, not sure if the removal of xml2-config is Debian specific

it is, AFAICT, upstream is not getting rid of it any time soon

> but I guess anyway it is better to use pkg-config if possible.

agreed.

Can you please then provide that reference directly in the commit
message, so anyone can be immediately clear what is this a result
of, please?

* * *

Also, regarding what was raised before (concurrently open PR):
https://github.com/Cluste2222rLabs/booth/pull/77#discussion_r322220732

I took a look and based on `xmlReadDoc`, minimal `libxml2` version
required is `v2.7.4`:

https://gitlab.gnome.org/GNOME/libxml2/commit/16fa96c5d013ef465b4db98170c435eeded0c4d4

Therefore, if there's no other aligned implication (no `libxml-2.0.pc`
file shipped back then, for instance, haven't checked), `configure`
shall IMHO _not_ be happy with arbitrary `libxml2` version.

So either that version shall be conditionalized for in
`PKG_CHECK_MODULES`, or `AC_CHECK_LIB([xml2], [xmlReadDoc])`
idea shall be retained, I think.

**Comment by jnpkrn** [comment]
Thanks

**Comment by dmuhamedagic** [comment]
Thanks!

**Pull request merged**
