### PR TITLE
fix bashisms (use printf instead of echo)

### PR DESCRIPTION
**Pull request by dmuhamedagic**

### CODE REVIEW

**Comment by fabbione** [comment]
add to whitelist

**Comment by fabbione** [comment]
@dmuhamedagic the comment I added is to tell CI that your PRs should be automatically tested. Sorry I forgot to add you as admin in the beginning.

**Review by jfriesse — APPROVED** [review]
Patch looks great so ACK by me.

**Comment by jfriesse** [comment]
@knet-ci-bot retest this please

**Comment by jfriesse** [comment]
@dmuhamedagic Please ignore Ci failures (at least for now) - I'm working on PR (#111) to make test pass.

**Pull request merged**
