### PR TITLE
Make use of git-version-gen and improve RPM building

### PR DESCRIPTION
**Pull request by jfriesse**
I know this patchset looks scary, so please don't hesitate to ask me questions. Basic idea is to use git-version-gen to generate version and improve RPM build process so it can be used in knet-ci (test RPM build https://ci.kronosnet.org/view/booth/job/booth-build-rpms/) for other projects as dependency and possibly for users who seek for newest RPM of booth.

I was thinking about splitting patchset a bit, but sadly there are too many dependencies, (first 5 patches can be applied independently tho)

### CODE REVIEW

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
Patch looks good to me. It´s pretty much the same code we use across libqb/corosync/knet/etc to build git versioned rpms.

**Comment by dmuhamedagic** [comment]
I'm still not sure what is git-version-gen good for, but it seems
to be in widespread use. Please just replace bashisms, e.g.
there's '==' in test(1) a few times.

**Comment by fabbione** [comment]
@dmuhamedagic basically, the git-version-gen is a script that is capable of determining the current version of the tree, based on the last tag + amount of commits on top of it, on the current branch. This way we are capable of generating proper rpm versions from git, maintaining an upgrade path without relying on the sha1.

For example:
libknet1-1.90-1.496.7cde.x86_64.rpm

knet release with tag v1.90, 1496 commits on top of the tag, 7cde <- git sha1 (reduced)

**Comment by jfriesse** [comment]
@dmuhamedagic Thank you for the review. I have nothing to add to explanation provided by @fabbione, but please don't hesitate to ask more if purpose of this PR is unclear.

I've added commit https://github.com/ClusterLabs/booth/pull/97/commits/190e01458cc27e634eaa99b502bc472a08ec4fd3 which removes bashisms. I've tried checkbashisms script (found only `==` problem as you've pointed out) and running full build (autoreconf -fvi && ./configure --without-glue && make && make rpm) using dash as /bin/sh and login shell for user and it worked flawlessly.

**Comment by fabbione** [comment]
retest this please

**Pull request merged**
