### PR TITLE
tests: Remove the unit-tests directory.

### PR DESCRIPTION
**Pull request by clumens**
This code doesn't work and hasn't been touched in several years.  There are other ways to test booth that do work, and the fact that no one has fixed these tests means that no one thinks they are important enough to get working.  So, remove them.

### CODE REVIEW

**Comment by clumens** [comment]
As discussed in email, the unit-tests directory doesn't appear to do anything useful.  Our options are leave it alone (which is what fooled me), try to fix it (which doesn't seem like a priority given it hasn't been touched in years), or remove it.  Here's a patch that does the last.

**Comment by jfriesse** [comment]
retest this please

**Comment by jfriesse** [comment]
@clumens I can agree with removing unmaintained tests. Just note it is failing and there are two reasons:
1. Make rpm fails (it is trying to package now non-existing directory)
2. make check fails on kernel 6.9 - I'm investigating this one. It looks like netlink interface now behaves a little bit different and booth handles it incorrectly. I'm working on smaller patch to fix it but longer term I would recommend to rewrite the code to use getifaddrs - it is more portable and hopefully more stable interface.

**Comment by clumens** [comment]
>     1. Make rpm fails (it is trying to package now non-existing directory)

Fixed.

>     2. make check fails on kernel 6.9 - I'm investigating this one. It looks like netlink interface now behaves a little bit different and booth handles it incorrectly. I'm working on smaller patch to fix this problem but longer term I would recommend to rewrite the code to use getifaddrs - it is more portable and hopefully more stable interface.

If you want to file an issue to deal with switching to getifaddrs, go for it.  I'll take a look at some point.  My current plan is to work on the crm_ticket stuff, then look through any refactoring/cleanup issues, then start to look at these kinds of improvements.

**Comment by jfriesse** [comment]
@clumens Perfect. I've fixed rawhide issue - https://github.com/ClusterLabs/booth/pull/139 so I think it make sense to review/merge this first, rebase this PR on top of new main head and run CI again.

RFE Issue filled https://github.com/ClusterLabs/booth/issues/140.

**Review by jfriesse — APPROVED** [review]

**Pull request merged**
